//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagerWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkRecordEntities : DbContext
    {
        public WorkRecordEntities()
            : base("name=WorkRecordEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobDetail> JobDetail { get; set; }
        public virtual DbSet<JobRecord> JobRecord { get; set; }
        public virtual DbSet<JobSheet> JobSheet { get; set; }
        public virtual DbSet<JobMember> JobMember { get; set; }
        public virtual DbSet<MessageConfig> MessageConfig { get; set; }
        public virtual DbSet<MemberInfo> MemberInfo { get; set; }
    }
}
